### ISSUE TITLE
Broken colors

### ISSUE THREAD

**Issue by glyh** [MahdyMirzade/nyxt#3]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

![image](https://user-images.githubusercontent.com/12870742/147756281-46b5eff2-c223-4af0-a8c8-e03cc70b6064.png)

As the image shows. 

BTW, is there a way to hook into nyxt or something so that the color showed up in dark theme, rather than in white and update itself to dark?

**Comment by MahdiMirzadeh** [comment]
> Broken colors

Sorry for the 3month delay, Fixed this issue for nyxt browser's 2.2.4 update.

> BTW, is there a way to hook into nyxt or something so that the color showed up in dark theme, rather than in white and update itself to dark?

As far as I tried, it wasn't possible to change, **nyxt browser** first loads the page, then applies the rules of the dark-mode stylesheet.
However you can set something regarding default system's theme to dark so websites that support dark mode won't flash your eyes.
For instance you can add this in the end of your `stylesheet.css` file:
```
;; This automatically darkens WebKit-native interfaces and sends the
;; "prefers-color-scheme: dark" to all the supporting websites.
(setf (uiop:getenv "GTK_THEME") "Adwaita:dark")
```

Preview of the fix in latest commit:
![image](https://user-images.githubusercontent.com/63877463/160235992-bf20a883-06df-4b97-9f65-46ffd1d21bfd.png)
```
OS: Arch Linux
Version: nyxt 3-1 (aur)
```

**Comment by MahdiMirzadeh** [comment]
More screenshots:
![image](https://user-images.githubusercontent.com/63877463/160236547-6eefc2f8-9811-4377-b69a-9dcacf050f39.png)
![image](https://user-images.githubusercontent.com/63877463/160236568-a733c458-048c-4e90-955d-8fdaa446b86c.png)

**Comment by glyh** [comment]
Thank you!
